name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
    
      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Compile and Test
        run: sbt g8Test
