name: Update Dependency Graph

on:
  push:
    branches:
      - master

jobs:
  update-dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Submit Dependency Graph
        uses: scalacenter/sbt-dependency-submission@v2
