on:
  schedule:
    - cron: '0 2 * * 3'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-email: janjaali-scala-steward@users.noreply.github.com
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
